# Welcome to Impatient-Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: 9tailors
# email: your-email@domain.com
description: Design It Yourself!
# twitter_username: bdavidxyz
# github_username:  bdavidxyz
timezone: America/New_York

excerpt_separator: <!-- more -->

permalink: /:year/:month/:title

# Collections
collections_dir: collections
collections:
  pages:
    output: true
    permalink: :collection/:name

# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  # NODE
  - node_modules
  - package.json
  - package-lock.json
  # GULP
  - gulpfile.js
  # RUBY
  - Gemfile
  - Gemfile.lock
  # ETC
  - README.md
  - "*.log"
