---
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
- type: directory
  path: collections/_pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: collections/_posts
  label: Posts
  create: all
  match: "**/*"
  templates: post-attributes
- type: directory
  path: collections/_authors
  label: Authors
  create: all
  match: "**/*"
  templates: author-attributes
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path:
file_template: ":filename:"
